# Generated by Django 4.0.2 on 2022-02-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carts_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
