# Generated by Django 4.0.2 on 2022-02-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_privat24transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Privat24Transaction',
        ),
    ]
